import '../../models/rencloud_plan.dart';

class RenCloudCatalogData {
  static const List<Map<String, String>> categories = [
    {'id': 'all', 'name': 'All Services (55)'},
    {'id': 'mc_budget', 'name': 'Minecraft Budget (DDR4)'},
    {'id': 'mc_premium', 'name': 'Minecraft Premium (DDR5)'},
    {'id': 'mc_enterprise', 'name': 'Minecraft Enterprise'},
    {'id': 'vps_intel', 'name': 'VPS — Intel Platinum'},
    {'id': 'vps_epyc', 'name': 'VPS — AMD EPYC Milan'},
    {'id': 'vps_ryzen', 'name': 'VPS — AMD Ryzen 7950X'},
    {'id': 'hytale', 'name': 'Hytale Hosting'},
    {'id': 'ark', 'name': 'ARK: Ascended'},
    {'id': 'web', 'name': 'Web Hosting'},
    {'id': 'bot', 'name': 'Discord Bot Hosting'},
    {'id': 'vip', 'name': 'VIP Memberships'},
    {'id': 'setup', 'name': 'Setup Services'},
  ];

  static const List<RenCloudPlan> plans = [
    // 1. MINECRAFT BUDGET (DDR4)
    RenCloudPlan(
      id: 'mc_b_1',
      name: 'Dirt',
      categoryId: 'mc_budget',
      categoryName: 'Minecraft Budget (DDR4)',
      ram: '2 GB',
      nvmeStorage: '10 GB NVMe',
      cpu: '100% (1 Core)',
      monthlyPriceInr: 20,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'mc_b_2',
      name: 'Stone',
      categoryId: 'mc_budget',
      categoryName: 'Minecraft Budget (DDR4)',
      ram: '4 GB',
      nvmeStorage: '20 GB NVMe',
      cpu: '200% (2 Cores)',
      monthlyPriceInr: 40,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'mc_b_3',
      name: 'Iron',
      categoryId: 'mc_budget',
      categoryName: 'Minecraft Budget (DDR4)',
      ram: '8 GB',
      nvmeStorage: '30 GB NVMe',
      cpu: '300% (3 Cores)',
      monthlyPriceInr: 80,
      isPopular: true,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'mc_b_4',
      name: 'Redstone',
      categoryId: 'mc_budget',
      categoryName: 'Minecraft Budget (DDR4)',
      ram: '16 GB',
      nvmeStorage: '40 GB NVMe',
      cpu: '400% (4 Cores)',
      monthlyPriceInr: 160,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'mc_b_5',
      name: 'Gold',
      categoryId: 'mc_budget',
      categoryName: 'Minecraft Budget (DDR4)',
      ram: '32 GB',
      nvmeStorage: '40 GB NVMe',
      cpu: '450% (4.5 Cores)',
      monthlyPriceInr: 320,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'mc_b_6',
      name: 'Emerald',
      categoryId: 'mc_budget',
      categoryName: 'Minecraft Budget (DDR4)',
      ram: '48 GB',
      nvmeStorage: '50 GB NVMe',
      cpu: '500% (5 Cores)',
      monthlyPriceInr: 480,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'mc_b_7',
      name: 'Netherite',
      categoryId: 'mc_budget',
      categoryName: 'Minecraft Budget (DDR4)',
      ram: '64 GB',
      nvmeStorage: '60 GB NVMe',
      cpu: '700% (7 Cores)',
      monthlyPriceInr: 640,
      tierType: 'Budget',
    ),

    // 2. MINECRAFT PREMIUM (DDR5)
    RenCloudPlan(
      id: 'mc_p_1',
      name: 'Premium Dirt',
      categoryId: 'mc_premium',
      categoryName: 'Minecraft Premium (DDR5)',
      ram: '2 GB',
      nvmeStorage: '10 GB NVMe',
      cpu: '100% (1 Core)',
      monthlyPriceInr: 40,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'mc_p_2',
      name: 'Premium Stone',
      categoryId: 'mc_premium',
      categoryName: 'Minecraft Premium (DDR5)',
      ram: '4 GB',
      nvmeStorage: '20 GB NVMe',
      cpu: '200% (2 Cores)',
      monthlyPriceInr: 80,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'mc_p_3',
      name: 'Premium Iron',
      categoryId: 'mc_premium',
      categoryName: 'Minecraft Premium (DDR5)',
      ram: '8 GB',
      nvmeStorage: '30 GB NVMe',
      cpu: '300% (3 Cores)',
      monthlyPriceInr: 160,
      isPopular: true,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'mc_p_4',
      name: 'Premium Redstone',
      categoryId: 'mc_premium',
      categoryName: 'Minecraft Premium (DDR5)',
      ram: '16 GB',
      nvmeStorage: '40 GB NVMe',
      cpu: '400% (4 Cores)',
      monthlyPriceInr: 320,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'mc_p_5',
      name: 'Premium Gold',
      categoryId: 'mc_premium',
      categoryName: 'Minecraft Premium (DDR5)',
      ram: '32 GB',
      nvmeStorage: '40 GB NVMe',
      cpu: '450% (4.5 Cores)',
      monthlyPriceInr: 640,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'mc_p_6',
      name: 'Premium Emerald',
      categoryId: 'mc_premium',
      categoryName: 'Minecraft Premium (DDR5)',
      ram: '48 GB',
      nvmeStorage: '50 GB NVMe',
      cpu: '500% (5 Cores)',
      monthlyPriceInr: 960,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'mc_p_7',
      name: 'Premium Netherite',
      categoryId: 'mc_premium',
      categoryName: 'Minecraft Premium (DDR5)',
      ram: '64 GB',
      nvmeStorage: '60 GB NVMe',
      cpu: '700% (7 Cores)',
      monthlyPriceInr: 1280,
      tierType: 'Premium',
    ),

    // 3. MINECRAFT ENTERPRISE
    RenCloudPlan(
      id: 'mc_e_1',
      name: 'Enterprise Dirt',
      categoryId: 'mc_enterprise',
      categoryName: 'Minecraft Enterprise',
      ram: '2 GB',
      nvmeStorage: '10 GB NVMe',
      cpu: '1 vCore (100%)',
      monthlyPriceInr: 99,
      tierType: 'Enterprise',
      databases: 1,
      backups: 1,
    ),
    RenCloudPlan(
      id: 'mc_e_2',
      name: 'Enterprise Stone',
      categoryId: 'mc_enterprise',
      categoryName: 'Minecraft Enterprise',
      ram: '4 GB',
      nvmeStorage: '25 GB NVMe',
      cpu: '2 vCores (200%)',
      monthlyPriceInr: 199,
      tierType: 'Enterprise',
      databases: 1,
      backups: 2,
    ),
    RenCloudPlan(
      id: 'mc_e_3',
      name: 'Enterprise Iron',
      categoryId: 'mc_enterprise',
      categoryName: 'Minecraft Enterprise',
      ram: '8 GB',
      nvmeStorage: '40 GB NVMe',
      cpu: '4 vCores (400%)',
      monthlyPriceInr: 399,
      isPopular: true,
      tierType: 'Enterprise',
      databases: 2,
      backups: 3,
    ),
    RenCloudPlan(
      id: 'mc_e_4',
      name: 'Enterprise Coal',
      categoryId: 'mc_enterprise',
      categoryName: 'Minecraft Enterprise',
      ram: '12 GB',
      nvmeStorage: '60 GB NVMe',
      cpu: '5 vCores (500%)',
      monthlyPriceInr: 599,
      tierType: 'Enterprise',
      databases: 3,
      backups: 4,
    ),
    RenCloudPlan(
      id: 'mc_e_5',
      name: 'Enterprise Redstone',
      categoryId: 'mc_enterprise',
      categoryName: 'Minecraft Enterprise',
      ram: '16 GB',
      nvmeStorage: '120 GB NVMe',
      cpu: '7 vCores (700%)',
      monthlyPriceInr: 799,
      tierType: 'Enterprise',
      databases: 4,
      backups: 5,
    ),
    RenCloudPlan(
      id: 'mc_e_6',
      name: 'Enterprise Diamond',
      categoryId: 'mc_enterprise',
      categoryName: 'Minecraft Enterprise',
      ram: '24 GB',
      nvmeStorage: '150 GB NVMe',
      cpu: '9 vCores (900%)',
      monthlyPriceInr: 1199,
      tierType: 'Enterprise',
      databases: 5,
      backups: 6,
    ),
    RenCloudPlan(
      id: 'mc_e_7',
      name: 'Enterprise Gold',
      categoryId: 'mc_enterprise',
      categoryName: 'Minecraft Enterprise',
      ram: '32 GB',
      nvmeStorage: '240 GB NVMe',
      cpu: '12 vCores (1200%)',
      monthlyPriceInr: 1599,
      tierType: 'Enterprise',
      databases: 6,
      backups: 7,
    ),

    // 4. CLOUD VPS — INTEL PLATINUM 8269-CY
    RenCloudPlan(
      id: 'vps_i_1',
      name: 'Platinum 8',
      categoryId: 'vps_intel',
      categoryName: 'Cloud VPS — Intel Platinum',
      ram: '8 GB DDR4',
      nvmeStorage: '50 GB NVMe',
      cpu: '2 vCores',
      monthlyPriceInr: 350,
    ),
    RenCloudPlan(
      id: 'vps_i_2',
      name: 'Platinum 16',
      categoryId: 'vps_intel',
      categoryName: 'Cloud VPS — Intel Platinum',
      ram: '16 GB DDR4',
      nvmeStorage: '80 GB NVMe',
      cpu: '4 vCores',
      monthlyPriceInr: 850,
      isPopular: true,
    ),
    RenCloudPlan(
      id: 'vps_i_3',
      name: 'Platinum 32',
      categoryId: 'vps_intel',
      categoryName: 'Cloud VPS — Intel Platinum',
      ram: '32 GB DDR4',
      nvmeStorage: '120 GB NVMe',
      cpu: '8 vCores',
      monthlyPriceInr: 1450,
    ),
    RenCloudPlan(
      id: 'vps_i_4',
      name: 'Platinum 48',
      categoryId: 'vps_intel',
      categoryName: 'Cloud VPS — Intel Platinum',
      ram: '48 GB DDR4',
      nvmeStorage: '150 GB NVMe',
      cpu: '10 vCores',
      monthlyPriceInr: 1950,
    ),
    RenCloudPlan(
      id: 'vps_i_5',
      name: 'Platinum 64',
      categoryId: 'vps_intel',
      categoryName: 'Cloud VPS — Intel Platinum',
      ram: '64 GB DDR4',
      nvmeStorage: '200 GB NVMe',
      cpu: '12 vCores',
      monthlyPriceInr: 2450,
    ),

    // 5. CLOUD VPS — AMD EPYC MILAN
    RenCloudPlan(
      id: 'vps_e_1',
      name: 'Milan 16',
      categoryId: 'vps_epyc',
      categoryName: 'Cloud VPS — AMD EPYC Milan',
      ram: '16 GB DDR4',
      nvmeStorage: '80 GB NVMe',
      cpu: '4 vCores',
      monthlyPriceInr: 1100,
    ),
    RenCloudPlan(
      id: 'vps_e_2',
      name: 'Milan 32',
      categoryId: 'vps_epyc',
      categoryName: 'Cloud VPS — AMD EPYC Milan',
      ram: '32 GB DDR4',
      nvmeStorage: '120 GB NVMe',
      cpu: '8 vCores',
      monthlyPriceInr: 1800,
      isPopular: true,
    ),
    RenCloudPlan(
      id: 'vps_e_3',
      name: 'Milan 48',
      categoryId: 'vps_epyc',
      categoryName: 'Cloud VPS — AMD EPYC Milan',
      ram: '48 GB DDR4',
      nvmeStorage: '150 GB NVMe',
      cpu: '10 vCores',
      monthlyPriceInr: 2300,
    ),
    RenCloudPlan(
      id: 'vps_e_4',
      name: 'Milan 64',
      categoryId: 'vps_epyc',
      categoryName: 'Cloud VPS — AMD EPYC Milan',
      ram: '64 GB DDR4',
      nvmeStorage: '200 GB NVMe',
      cpu: '12 vCores',
      monthlyPriceInr: 2600,
    ),
    RenCloudPlan(
      id: 'vps_e_5',
      name: 'Milan 64 Pro',
      categoryId: 'vps_epyc',
      categoryName: 'Cloud VPS — AMD EPYC Milan',
      ram: '64 GB DDR4',
      nvmeStorage: '200 GB NVMe',
      cpu: '16 vCores',
      monthlyPriceInr: 3100,
    ),

    // 6. CLOUD VPS — AMD RYZEN 9 7950X
    RenCloudPlan(
      id: 'vps_r_1',
      name: 'Ryzen 4',
      categoryId: 'vps_ryzen',
      categoryName: 'Cloud VPS — AMD Ryzen 7950X',
      ram: '4 GB DDR5',
      nvmeStorage: '50 GB NVMe',
      cpu: '1 vCore',
      monthlyPriceInr: 649,
    ),
    RenCloudPlan(
      id: 'vps_r_2',
      name: 'Ryzen 8',
      categoryId: 'vps_ryzen',
      categoryName: 'Cloud VPS — AMD Ryzen 7950X',
      ram: '8 GB DDR4',
      nvmeStorage: '80 GB NVMe',
      cpu: '2 vCores',
      monthlyPriceInr: 1149,
    ),
    RenCloudPlan(
      id: 'vps_r_3',
      name: 'Ryzen 16',
      categoryId: 'vps_ryzen',
      categoryName: 'Cloud VPS — AMD Ryzen 7950X',
      ram: '16 GB DDR4',
      nvmeStorage: '150 GB NVMe',
      cpu: '4 vCores',
      monthlyPriceInr: 1849,
      isPopular: true,
    ),
    RenCloudPlan(
      id: 'vps_r_4',
      name: 'Ryzen 24',
      categoryId: 'vps_ryzen',
      categoryName: 'Cloud VPS — AMD Ryzen 7950X',
      ram: '24 GB DDR4',
      nvmeStorage: '180 GB NVMe',
      cpu: '5 vCores',
      monthlyPriceInr: 2549,
    ),
    RenCloudPlan(
      id: 'vps_r_5',
      name: 'Ryzen 32',
      categoryId: 'vps_ryzen',
      categoryName: 'Cloud VPS — AMD Ryzen 7950X',
      ram: '32 GB DDR4',
      nvmeStorage: '200 GB NVMe',
      cpu: '6 vCores',
      monthlyPriceInr: 3449,
    ),
    RenCloudPlan(
      id: 'vps_r_6',
      name: 'Ryzen 48',
      categoryId: 'vps_ryzen',
      categoryName: 'Cloud VPS — AMD Ryzen 7950X',
      ram: '48 GB DDR4',
      nvmeStorage: '250 GB NVMe',
      cpu: '8 vCores',
      monthlyPriceInr: 4749,
    ),
    RenCloudPlan(
      id: 'vps_r_7',
      name: 'Ryzen 64',
      categoryId: 'vps_ryzen',
      categoryName: 'Cloud VPS — AMD Ryzen 7950X',
      ram: '64 GB DDR4',
      nvmeStorage: '300 GB NVMe',
      cpu: '10 vCores',
      monthlyPriceInr: 6149,
    ),

    // 7. HYTALE HOSTING
    RenCloudPlan(
      id: 'hytale_1',
      name: 'Hytale Starter',
      categoryId: 'hytale',
      categoryName: 'Hytale Hosting',
      ram: '4 GB DDR4',
      nvmeStorage: '20 GB NVMe',
      cpu: '200% (2 Cores)',
      monthlyPriceInr: 60,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'hytale_2',
      name: 'Hytale Regular',
      categoryId: 'hytale',
      categoryName: 'Hytale Hosting',
      ram: '8 GB DDR4',
      nvmeStorage: '40 GB NVMe',
      cpu: '400% (4 Cores)',
      monthlyPriceInr: 120,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'hytale_3',
      name: 'Hytale Pro',
      categoryId: 'hytale',
      categoryName: 'Hytale Hosting',
      ram: '8 GB DDR5',
      nvmeStorage: '40 GB NVMe',
      cpu: '400% (4 Cores)',
      monthlyPriceInr: 200,
      isPopular: true,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'hytale_4',
      name: 'Hytale Extreme',
      categoryId: 'hytale',
      categoryName: 'Hytale Hosting',
      ram: '16 GB DDR5',
      nvmeStorage: '80 GB NVMe',
      cpu: '800% (8 Cores)',
      monthlyPriceInr: 400,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'hytale_5',
      name: 'Hytale Dedicated',
      categoryId: 'hytale',
      categoryName: 'Hytale Hosting',
      ram: '32 GB DDR5',
      nvmeStorage: '120 GB NVMe',
      cpu: '1200% (12 Cores)',
      monthlyPriceInr: 800,
      tierType: 'Enterprise',
    ),

    // 8. ARK: SURVIVAL ASCENDED
    RenCloudPlan(
      id: 'ark_1',
      name: 'ARK Explorer',
      categoryId: 'ark',
      categoryName: 'ARK: Survival Ascended',
      ram: '8 GB DDR4',
      nvmeStorage: '50 GB NVMe',
      cpu: '300% (3 Cores)',
      monthlyPriceInr: 100,
      tierType: 'Budget',
    ),
    RenCloudPlan(
      id: 'ark_2',
      name: 'ARK Survival',
      categoryId: 'ark',
      categoryName: 'ARK: Survival Ascended',
      ram: '16 GB DDR4',
      nvmeStorage: '100 GB NVMe',
      cpu: '600% (6 Cores)',
      monthlyPriceInr: 300,
      isPopular: true,
      tierType: 'Premium',
    ),
    RenCloudPlan(
      id: 'ark_3',
      name: 'ARK Ascended',
      categoryId: 'ark',
      categoryName: 'ARK: Survival Ascended',
      ram: '32 GB DDR5',
      nvmeStorage: '200 GB NVMe',
      cpu: '1000% (10 Cores)',
      monthlyPriceInr: 600,
      tierType: 'Enterprise',
    ),

    // 9. WEB HOSTING
    RenCloudPlan(
      id: 'web_1',
      name: 'Starter Web',
      categoryId: 'web',
      categoryName: 'Web Hosting',
      ram: '1 GB',
      nvmeStorage: '10 GB NVMe SSD',
      cpu: '1 Core',
      monthlyPriceInr: 49,
    ),
    RenCloudPlan(
      id: 'web_2',
      name: 'Basic Web',
      categoryId: 'web',
      categoryName: 'Web Hosting',
      ram: '2 GB',
      nvmeStorage: '25 GB NVMe SSD',
      cpu: '2 Cores',
      monthlyPriceInr: 99,
    ),
    RenCloudPlan(
      id: 'web_3',
      name: 'Premium Web',
      categoryId: 'web',
      categoryName: 'Web Hosting',
      ram: '4 GB',
      nvmeStorage: '50 GB NVMe SSD',
      cpu: '4 Cores',
      monthlyPriceInr: 199,
      isPopular: true,
    ),
    RenCloudPlan(
      id: 'web_4',
      name: 'Business Web',
      categoryId: 'web',
      categoryName: 'Web Hosting',
      ram: '8 GB',
      nvmeStorage: '100 GB NVMe SSD',
      cpu: '6 Cores',
      monthlyPriceInr: 399,
    ),
    RenCloudPlan(
      id: 'web_5',
      name: 'Enterprise Web',
      categoryId: 'web',
      categoryName: 'Web Hosting',
      ram: '16 GB',
      nvmeStorage: '200 GB NVMe SSD',
      cpu: '8 Cores',
      monthlyPriceInr: 799,
    ),

    // 10. DISCORD BOT HOSTING
    RenCloudPlan(
      id: 'bot_1',
      name: 'Starter Bot',
      categoryId: 'bot',
      categoryName: 'Discord Bot Hosting',
      ram: '256 MB',
      nvmeStorage: '5 GB',
      cpu: '25% CPU',
      monthlyPriceInr: 20,
    ),
    RenCloudPlan(
      id: 'bot_2',
      name: 'Basic Bot',
      categoryId: 'bot',
      categoryName: 'Discord Bot Hosting',
      ram: '512 MB',
      nvmeStorage: '10 GB',
      cpu: '50% CPU',
      monthlyPriceInr: 40,
    ),
    RenCloudPlan(
      id: 'bot_3',
      name: 'Advanced Bot',
      categoryId: 'bot',
      categoryName: 'Discord Bot Hosting',
      ram: '1 GB',
      nvmeStorage: '20 GB',
      cpu: '100% CPU',
      monthlyPriceInr: 80,
      isPopular: true,
    ),
    RenCloudPlan(
      id: 'bot_4',
      name: 'Pro Bot',
      categoryId: 'bot',
      categoryName: 'Discord Bot Hosting',
      ram: '2 GB',
      nvmeStorage: '30 GB',
      cpu: '200% CPU',
      monthlyPriceInr: 160,
    ),
    RenCloudPlan(
      id: 'bot_5',
      name: 'Enterprise Bot',
      categoryId: 'bot',
      categoryName: 'Discord Bot Hosting',
      ram: '4 GB',
      nvmeStorage: '50 GB',
      cpu: '400% CPU',
      monthlyPriceInr: 320,
    ),

    // 11. VIP MEMBERSHIPS
    RenCloudPlan(
      id: 'vip_1',
      name: 'Cloud Membership',
      categoryId: 'vip',
      categoryName: 'VIP Memberships',
      ram: '8 GB Premium Allocation',
      nvmeStorage: 'VIP Discord Access',
      cpu: 'Priority Allocation',
      monthlyPriceInr: 149,
      extraInfo: '8 GB Premium Server allocation + VIP Discord role & channel access',
    ),
    RenCloudPlan(
      id: 'vip_2',
      name: 'Storm Membership',
      categoryId: 'vip',
      categoryName: 'VIP Memberships',
      ram: '16 GB Premium Allocation',
      nvmeStorage: 'Free Setup Services Included',
      cpu: 'Dedicated Priority Node',
      monthlyPriceInr: 299,
      isPopular: true,
      extraInfo: '16 GB Premium Server allocation + free setup services + VIP lounge',
    ),

    // 12. SETUP SERVICES (ONE-TIME)
    RenCloudPlan(
      id: 'setup_1',
      name: 'Custom Plugins Setup',
      categoryId: 'setup',
      categoryName: 'Setup Services',
      ram: 'N/A',
      nvmeStorage: 'Tailored Config',
      cpu: 'Expert Engineer',
      monthlyPriceInr: 1220,
      isOneTime: true,
      extraInfo: 'Tailored plugin setup & custom configuration by RenCloud engineers',
    ),
    RenCloudPlan(
      id: 'setup_2',
      name: 'Server Setups',
      categoryId: 'setup',
      categoryName: 'Setup Services',
      ram: 'N/A',
      nvmeStorage: 'Complete Optimization',
      cpu: 'Full Node Tuning',
      monthlyPriceInr: 1200,
      isOneTime: true,
      extraInfo: 'Complete end-to-end server setup, security hardening & performance tuning',
    ),
  ];
}
